### ISSUE TITLE
WalletConnect stuck at Connecting ...

### ISSUE THREAD

**Issue by olaf89** [TrustWallet/wallet-connect-swift#10]
After scanning Qr code trust wallet the code is read and redirect happen but its stuck at 

> "Connecting ..."

It happens quite a lot i would say 10% of cases.

I am using latest version of trust wallet and example app at https://example.walletconnect.org/

**Comment by hewigovens** [comment]
Hi, Did you scan the same qr code? we have a issue to track this: https://github.com/TrustWallet/wallet-connect-swift/issues/7

**Comment by olaf89** [comment]
When i san the same qr code then its always stuck. But then reloading the page often gives the same result

**Comment by johnnynanjiang** [comment]
Got the same issue once out of five tries.

**Comment by hewigovens** [comment]
This should be fixed in new iOS release
