### ISSUE TITLE
[question] how to get binance wallet address from trustwallet?

### ISSUE THREAD

**Issue by gruming** [TrustWallet/wallet-connect-swift#16]
I have dapp and connection to walletconnect from trustwallet.

How to get binance wallet address from trustwallet?

**Comment by hewigovens** [comment]
Take a look at this: https://developer.trustwallet.com/wallet-connect/dapp, you can call 
```js
walletConnector
  .getAccounts()
```

**Comment by gruming** [comment]
thx for comment !!!
