### ISSUE TITLE
Wallet SDK installation problem

### ISSUE THREAD

**Issue by shiiVaam** [TrustWallet/wallet-connect-swift#2]
Pod is not installing.
![Screenshot 2019-04-24 at 6 49 32 PM](https://user-images.githubusercontent.com/29759955/56662505-c1f08f00-66c1-11e9-9e3f-c36cd626c18a.png)
![Screenshot 2019-04-24 at 6 49 32 PM](https://user-images.githubusercontent.com/29759955/56662508-c321bc00-66c1-11e9-9df1-d6ebbb9f1a57.png)

**Comment by hewigovens** [comment]
could you please try:

1. `pod 'WalletConnect', git: 'https://github.com/TrustWallet/wallet-connect-swift', branch: 'master'`
2. update your cocoapods

**Comment by shiiVaam** [comment]
I have done it. 
1. Opened podfile in Atom.
2. Copied pod 
It gave me same error mentioned in the attached screenshots.

**Comment by hewigovens** [comment]
Did you run `pod install` inside `wallet-connect-swift/Example`? in this case you don't need to edit the `Podfile`

**Comment by shiiVaam** [comment]
I have done it sir.
You can see that my directory is Example in screenshot

**Comment by hewigovens** [comment]
it works for me:

```
1. download zip
2. cd Example
3. pod install
```

![image](https://user-images.githubusercontent.com/360470/56724221-258bc280-677d-11e9-9e6b-2e5a6b0333b8.png)

**Comment by shiiVaam** [comment]
successfully installed .
In xcode , it gave an error
![Screenshot 2019-04-25 at 2 56 43 PM](https://user-images.githubusercontent.com/29759955/56725440-79d97700-676a-11e9-8008-d0325d5a3679.png)

**Comment by hewigovens** [comment]
please run `gem install cocoapods` to update cocoapods to 1.6.1
