### ISSUE TITLE
Personel_sign in rejected

### ISSUE THREAD

**Issue by rachkumar** [trustwallet/wallet-connect-swift#26]
Hi,
    Am trying to Personel_sign, but am getting issue as call request rejected.

   What I tried:
   1.)Added SDK to my project.
   2.)I can able to scan and connect.
   But Cant able to personal_sign..
   Please help to find the solution for this..

**Comment by hewigovens** [comment]
could you please share your detail code? you need to handle `personal_sign` inside your app, this lib only parses and presents you the data to sign
