### ISSUE TITLE
Value of type 'WebSocket' has no member 'onConnect'

### ISSUE THREAD

**Issue by zhaojiewen** [trustwallet/wallet-connect-swift#33]
compiler error

**Comment by zhaojiewen** [comment]
pod 'Starscream',git: 'https://github.com/daltoniam/Starscream' , tag: '3.1.1'  
fix it

**Comment by hewigovens** [comment]
btw we won't upgrade to latest Starscream, we will replace it with builtin URLSessionWebSocketTask
