### ISSUE TITLE
Issue using Wallet Connect

### ISSUE THREAD

**Issue by anxolin** [trustwallet/wallet-connect-swift#34]
Hello, for some reason TrustWallet seems to not work any more with Wallet Connect 

We've received lot's of reports of issues that all they have Trust Wallet in common. The most common error we see of those is:
`gas required exceeds allowance (11720486) or always failing transaction (-32000)`

Gnois Safe:
![image](https://user-images.githubusercontent.com/2352112/86046510-9c8dac80-ba4d-11ea-972e-25ef14ca7485.png)

Mesa:
![image](https://user-images.githubusercontent.com/2352112/86046519-a0b9ca00-ba4d-11ea-9ddf-f6361fc56b01.png)

The two examples, are two dapps where is currently failing any transaction.
* http://mesa.eth.link/
* https://gnosis-safe.io/app

We thought at first it could be a bad "Gas Limit" estimation in Trust Wallet. But if we provide the `gas` information in the transaction config, we still get the same error. Even if we overestimate it.

I believe this was working on the past, so it must be something more or less recent. 
Can you help me with this issue?

**Comment by hewigovens** [comment]
Thanks for reporting, will debug it later, I had same error before (zero balance will cause gas estimate always failed)

**Comment by hewigovens** [comment]
@anxolin I tried http://mesa.eth.link/ with WETH approval tx: 

https://etherscan.io/tx/0x3882fa0522df212423299cc486b6f9ce10ba128d6f9c000523593a332aff7154

The request was below, note no `gas` or `gasLimit`

```json
{
    "id": 1593598816011953,
    "jsonrpc": "2.0",
    "method": "eth_sendTransaction",
    "params": [{
        "from": "0x7d8bf18c7ce84b3e175b339c4ca93aed1dd166f1",
        "to": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
        "gasPrice": "0x9c81e1442",
        "data": "0x095ea7b30000000000000000000000006f400810b62df8e13fded51be75ff5393eaa841fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
    }]
}
```

**Comment by anxolin** [comment]
Hei @hewigovens! 

Thanks for taking a look to this.

Yes, after creating the issue I was talking to @vikmeup. Sorry I forgot to report back here. 
We were aware we don't send the `gasLimit`. All the other wallets we use estimate, and I believe in the past either directly or indirectly (geth) I think Trust Wallet was estimating, because we didn't observe any issues some time ago.

We'll add soon the gas limit to ensure compatibility!

**Comment by vikmeup** [comment]
> Hei @hewigovens!
> 
> Thanks for taking a look to this.
> 
> Yes, after creating the issue I was talking to @vikmeup. Sorry I forgot to report back here.
> We were aware we don't send the `gasLimit`. All the other wallets we use estimate, and I believe in the past either directly or indirectly (geth) I think Trust Wallet was estimating, because we didn't observe any issues some time ago.
> 
> We'll add soon the gas limit to ensure compatibility!

I suggest you never trust any providers to estimate anything for you, the more accurate you are the better.

Latest version of WalletConect does calculation, but we never advise to delegate this to the wallet side. You should not trust other providers - always trust your code instead.
