### ISSUE TITLE
Update CryptoSwift version

### ISSUE THREAD

**Issue by AyushBherwani1998** [trustwallet/wallet-connect-swift#43]
With Xcode 12.5, I'm not able to build project because it uses older version of CryptoSwift. Here's the open issue https://github.com/krzyzanowskim/CryptoSwift/issues/864

**Comment by hewigovens** [comment]
This repo is not actively maintained, I think you can just fork and update `CryptoSwift` to latest version

**Comment by AyushBherwani1998** [comment]
Sure, closing this ticket.
