### ISSUE TITLE
WalletConnect eth_sendTransaction default values are invalid

### ISSUE THREAD

**Issue by olaf89** [trustwallet/wallet-connect-swift#6]
## Expected Behavior

When the gas price is not provided the value is preset using user transaction cost configuration.
When the nonce is not provided the value is preset, accounting for network/local latest nonce.

## Current Behavior

The nonce and gasPrice is set to 0 so even tho defaults are provided they will never work.

## Steps to Reproduce (for bugs)

Send transaction with nonce and gasPrice not preset by dapp.

## Context

I expect WalletConnect integration to work the same way as web3 browser injected provider.

**Comment by vikmeup** [comment]
@hewigovens what's needed for this?

**Comment by hewigovens** [comment]
The app needs to check and fetch missing fields before sending tx

**Comment by hewigovens** [comment]
Trust iOS has fixed this
